# Dockerfile for node-todo
FROM node:latest

# Set working directory
WORKDIR /app

# Copy build files
COPY ./dist/apps/node-todo ./

# Install dependencies
RUN npm i

# Expose the port (if you are serving the app on a specific port)
EXPOSE 3000

# # Start the app
CMD ["node", "main.js"]
